### ISSUE TITLE
Plugin consumes command line arguments for XJC

### ISSUE THREAD

**Issue by Nogyara** [Hubbitus/xjc-documentation-annotation-plugin#1]
Whis causes this plugin to be unusable with other XJC plugins :(.
The fix is simple though:

info.hubbitus.XJCPluginDescriptionAnnotation#parseArgument should return 0 instead of 1

**Comment by Hubbitus** [comment]
Thank you for the bugreport. But could you please more describe issue? How to reproduce? May be simple project demonstrating issue?

**Comment by Nogyara** [comment]
It's been a while but from what I remember, the problem occured when I tried to use your plugin alongside other plugins. In such case, there are multiple arguments for JAXB plugins to be parsed from command line and because of the wrong implementation of parseArgument() method, it consumes too much from the command line arguments thus corrupting remaining part of the command line to be consumed by following plugins (so yes, I think order of plugins when running XJC matters too).

You should be able to reproduce it pretty easily, just run XJC with your plugin first followed by another JAXB plugin (with some configuration on command line)

**Comment by Hubbitus** [comment]
@Nogyara, according to the [documentation](http://javadox.com/com.sun.xml.bind/jaxb-xjc/2.2.6/com/sun/tools/xjc/Plugin.html#parseArgument%28com.sun.tools.xjc.Options,%20java.lang.String[],%20int%29) it sounds strange to see "Returns: 0 if the argument is not understood.". But really plugin do not accept any arguments and there should be 0 parsed arguments. You are right.
